### ISSUE TITLE
Build initial GET querying TMD API

### ISSUE THREAD

**Issue by tiQu** [BCIT-SSD-2020-21/dotnetproject-team7_dotnetproject_backend#11]

**Comment by jianmingtu** [comment]
![](https://i.imgur.com/PlSBI2Q.png)

**Comment by jianmingtu** [comment]
request:  https://localhost:44367/api/movie

Response 200
[
    {
        "backdrop_path": "/mXouvrZbn8YpZMURGvw30QK8qfo.jpg",
        "first_air_date": "2019-08-22",
        "id": 89641,
        "name": "Love Alarm",
        "original_language": "ko",
        "original_name": "좋아하면 울리는",
        "overview": "Love Alarm is an app that tells you if someone within a 10-meter radius has a crush on you. It quickly becomes a social phenomenon. While everyone talks about it and uses it to test their love and popularity, Jojo is one of the few people who have yet to download the app. However, she soon faces a love triangle situation between Sun-oh whom she starts to have feelings for, and Hye-young, who has had a huge crush on her.",
        "popularity": 166.605,
        "poster_path": "/s87JyAWtRLLlmsYWXTED1l8henB.jpg",
        "vote_average": 8.4,
        "vote_count": 577,
        "movieGenre": [
            {
                "movieId": 89641,
                "genreId": 18,
                "genre": {
                    "id": 18,
                    "name": "Drama",
                    "movieGenre": []
                }
            },
            {
                "movieId": 89641,
                "genreId": 10765,
                "genre": {
                    "id": 10765,
                    "name": "Annimation",
                    "movieGenre": []
                }
            }
        ]
    }

**Comment by jianmingtu** [comment]
request: https://localhost:44367/api/movie/89641
Response 200
[
{
"backdrop_path": "/mXouvrZbn8YpZMURGvw30QK8qfo.jpg",
"first_air_date": "2019-08-22",
"id": 89641,
"name": "Love Alarm",
"original_language": "ko",
"original_name": "좋아하면 울리는",
"overview": "Love Alarm is an app that tells you if someone within a 10-meter radius has a crush on you. It quickly becomes a social phenomenon. While everyone talks about it and uses it to test their love and popularity, Jojo is one of the few people who have yet to download the app. However, she soon faces a love triangle situation between Sun-oh whom she starts to have feelings for, and Hye-young, who has had a huge crush on her.",
"popularity": 166.605,
"poster_path": "/s87JyAWtRLLlmsYWXTED1l8henB.jpg",
"vote_average": 8.4,
"vote_count": 577,
"movieGenre": [
{
"movieId": 89641,
"genreId": 18,
"genre": {
"id": 18,
"name": "Drama",
"movieGenre": []
}
},
{
"movieId": 89641,
"genreId": 10765,
"genre": {
"id": 10765,
"name": "Annimation",
"movieGenre": []
}
}
]
}

**Comment by jianmingtu** [comment]
@Tilman Queitsch,   finally merged from main,  installed Microsoft.EntityFrameworkCore.Analyzers  because compile error. now,  I am going to test seeder.

**Comment by jianmingtu** [comment]
useful link to themoviedb

https://api.themoviedb.org/3/discover/tv?api_key=4d50e231ebab0b714167607ce53b71f1&language=en-US&with_original_language=ko

AND

https://developers.themoviedb.org/3/genres/get-tv-list
