### ISSUE TITLE
Create ViewModel from Seeder Data

### ISSUE THREAD

**Issue by thebcitguy** [BCIT-SSD-2020-21/dotnetproject-team7_dotnetproject_backend#13]
Will aim to create a ViewModel after Seeder Data is completed.

**Comment by philweier** [comment]
Thoughts re: this issue.
Currently seeding Movies, Genres, and bridge table MovieGenre. Api calls will expose a list of movies, list of genres to the front-end home page. We want a ViewModel that will hold the Movie collection from _db.Movies and the Genre collection from _db.Genre. The viewmodel will be serialized to JSON and the client will render the movies to a list and the genres to select element options for filtering.

Filtering Issue...
Option 1: We have the FULL movie collection with genres in the model...user selects the filter option and the filter is performed in the client.
Option 2: We have the FULL movie collection without genres...the use selects the filter option and we hit the api and get a fresh collection.
Option 3:  We have a paginated movie collection without genres...user selects a filter, or toggles pagination and we hit the api and get a fresh collection. (Api takes three )

**Comment by tiQu** [comment]
Completed as part of #45
