### ISSUE TITLE
Populate project db from TMDB (replaces seeder with dynamic data source)

### ISSUE THREAD

**Issue by tiQu** [BCIT-SSD-2020-21/dotnetproject-team7_dotnetproject_backend#20]
We have the go-ahead to query The Movie Database with an API key previously used for the React lab (see Slack) so we can populate our own database

**Comment by tiQu** [comment]
1) pull the master branch from the backend project
2) create own branch in Visual studio called "20OwenPullTMDB"
3) review documentation at https://developers.themoviedb.org (API key is in Slack)
4) write a new class / function that queries the TMDB API, gets the JSON and builds a collection of Movie items

**Comment by tiQu** [comment]
Hi @thebcitguy , we didn't get an update from you on Slack here, nor is the discussed branch pushed up to GitHub. Would have been great to have your code so we could continue to build on it.

**Comment by thebcitguy** [comment]
Implemented TMDB API so that users can search any actor by name and get their complete details. 
Please modify this according to the needs of the project.

**Comment by tiQu** [comment]
@thebcitguy Can't find a record of your branch (discussed name was 20OwenPullTMDB). Looks like you committed directly to the master branch instead. This can put the team's work in peril without someone in PST being able to review your changes. Please **do not** commit directly to master.

**Comment by thebcitguy** [comment]
@tiQu After you told me "you might have to pull the master branch again before you work on your own branch or resolve merge conflicts later", I deleted my initial branch "20.OwenPullTMDB", pulled the changes from the master branch and recreated a new branch "20.OwenPullTMDB". As such, I committed the changed to my new branch. I didn't know how it ended up in the master branch. Why would I want to commit directly to master?

![image](https://user-images.githubusercontent.com/71310642/101902503-b5e67780-3bed-11eb-9be2-175c90b09639.png)

**Comment by tiQu** [comment]
@thebcitguy your commits are showing up directly on master:

![image](https://user-images.githubusercontent.com/7821039/101940271-15676780-3b9b-11eb-89e2-ae2b8fbc0c25.png)

**Comment by tiQu** [comment]
@thebcitguy again, I can't verify on my end how this happened. Here's a new remote branch for you to work on:
https://github.com/BCIT-SSD-2020-21/dotnetproject-team7_dotnetproject_backend/tree/20OwenPullTMDB/

**Comment by tiQu** [comment]
> Implemented TMDB API so that users can search any actor by name and get their complete details.
> Please modify this according to the needs of the project.

Hi @thebcitguy , tried running the code on my machine. Some feedback:
- Searching by actor wasn't part of the issue requirement at all. What we needed was a function that converts incoming JSON to **Movie** objects for our database. 
- The code doesn't run for me. I'm getting build errors so I can't verify if it's actually functional. Also not sure what name.cs is for? Just seems to be an empty class
- To get a better understanding of how the API works, maybe run it on your local machine and query it with Postman or through your browser as done for the API we crated in class

**Comment by tiQu** [comment]
This has been completed as part of issues #11 and #16
