### ISSUE TITLE
Create seeder class for MovieUser Id (MovieUser table, RatingController)

### ISSUE THREAD

**Issue by tiQu** [BCIT-SSD-2020-21/dotnetproject-team7_dotnetproject_backend#40]
**Current status:**
We have a bridge table called MovieUser where ratings of movies by authenticated users are stored. It can be found in the ERD:
https://github.com/BCIT-SSD-2020-21/dotnetproject-team7_dotnetproject (scroll down to view ERD)
Constraints on the data can be found in the class C# file: **Models/MovieUser.cs**. 

**What we need:**
Eventually the frontend will pull data from this bridge table to render average movie ratings, for which we need data. Just like the Product seeder data class that Phil demonstrated in the course, we require a seeder class that adds dummy data asynchronously to the MovieUser table. This should trigger when the API is running and there are no records (i.e. no ratings) in the table. Ideally we would have ratings for each movie, though it's okay if not all of them have one. Any progress is progress 👍 

**Need to keep in mind:**
The MovieUser table needs three inputs: MovieId, UserId, and Rating (1-5). The MovieUserId is an autogenerated key. It is important that the MovieId values added in the seeder data are actual IDs from movies that we have in our database. Multiple ratings per Movie would be awesome.

**Comment by tiQu** [comment]
Thanks and please keep us posted @thebcitguy

**Comment by tiQu** [comment]
Thanks, and please keep us posted @thebcitguy . If we need to pick this up tomorrow morning PST we'll have to know.

**Comment by thebcitguy** [comment]
Experiencing some technical glitch relating to creating a separate branch for this issue. The branch has been created under Master. I suggest not pulling any changes in the meantime in case the changes get pulled into Master. Thanks.

![image](https://user-images.githubusercontent.com/71310642/102172899-c12ef100-3ed4-11eb-85ec-a77811836bc0.png)

**Comment by thebcitguy** [comment]
Completed creating seeder class and data.

**Comment by tiQu** [comment]
Thanks for the heads-up about the glitch. Master branch looks clean. 

Some feedback:
- Did you test this? I pulled the latest version of your branch and am still getting build errors, so this doesn't look completed
- The DbContext for the bridge table already exists (MovieDbContext). No need to create a new one
- The context you created isn't registered in the startup file so the application won't know about it

**Comment by tiQu** [comment]
No further progress on this. We'll have to move on without this piece since it's not essential. Side note: the API has been tested without seeded ratings through Postman.
